pipeline {

agent{
docker{
image 'python:2.7.16-slim'
args '--user root'
}
}

stages{
stage(build){
when {
changeset "**/vote/**"
}
steps{
echo 'Compiling vote app'
dir('result'){
sh 'pip install -i requirements.txt'
}
}
}
stage(test){
when {
changeset "**/vote/**"
}
steps{
echo 'Running Unit Tests on vote app'
dir ('result'){
sh 'nosetests -v'
}
}
}
}
 post{
 always{
 echo 'Building multibranch pipeline for worker is completed..'
 }
 failure{
 slackSend (channel: "instavote-cd", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
 }
 success{
 slackSend (channel: "instavote-cd", message: "Build Succeeded and OK - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
 }
 }
}
